# Setup list of patches and books to use
#

import os
import codecs

bookKeys = {
u'GEN': u'001',
u'EXO': u'002',
u'LEV': u'003',
u'NUM': u'004',
u'DEU': u'005',
u'JOS': u'006',
u'JDG': u'007',
u'RUT': u'008',
u'1SA': u'009',
u'2SA': u'010',
u'1KI': u'011',
u'2KI': u'012',
u'1CH': u'013',
u'2CH': u'014',
u'EZR': u'015',
u'NEH': u'016',
u'EST': u'017',
u'JOB': u'018',
u'PSA': u'019',
u'PRO': u'020',
u'ECC': u'021',
u'SNG': u'022',
u'ISA': u'023',
u'JER': u'024',
u'LAM': u'025',
u'EZK': u'026',
u'DAN': u'027',
u'HOS': u'028',
u'JOL': u'029',
u'AMO': u'030',
u'OBA': u'031',
u'JON': u'032',
u'MIC': u'033',
u'NAM': u'034',
u'HAB': u'035',
u'ZEP': u'036',
u'HAG': u'037',
u'ZEC': u'038',
u'MAL': u'039',
u'MAT': u'040',
u'MRK': u'041',
u'LUK': u'042',
u'JHN': u'043',
u'ACT': u'044',
u'ROM': u'045',
u'1CO': u'046',
u'2CO': u'047',
u'GAL': u'048',
u'EPH': u'049',
u'PHP': u'050',
u'COL': u'051',
u'1TH': u'052',
u'2TH': u'053',
u'1TI': u'054',
u'2TI': u'055',
u'TIT': u'056',
u'PHM': u'057',
u'HEB': u'058',
u'JAS': u'059',
u'1PE': u'060',
u'2PE': u'061',
u'1JN': u'062',
u'2JN': u'063',
u'3JN': u'064',
u'JUD': u'065',
u'REV': u'066'
}

silNames = [
u'GEN',
u'EXO',
u'LEV',
u'NUM',
u'DEU',
u'JOS',
u'JDG',
u'RUT',
u'1SA',
u'2SA',
u'1KI',
u'2KI',
u'1CH',
u'2CH',
u'EZR',
u'NEH',
u'EST',
u'JOB',
u'PSA',
u'PRO',
u'ECC',
u'SNG',
u'ISA',
u'JER',
u'LAM',
u'EZK',
u'DAN',
u'HOS',
u'JOL',
u'AMO',
u'OBA',
u'JON',
u'MIC',
u'NAM',
u'HAB',
u'ZEP',
u'HAG',
u'ZEC',
u'MAL',
u'MAT',
u'MRK',
u'LUK',
u'JHN',
u'ACT',
u'ROM',
u'1CO',
u'2CO',
u'GAL',
u'EPH',
u'PHP',
u'COL',
u'1TH',
u'2TH',
u'1TI',
u'2TI',
u'TIT',
u'PHM',
u'HEB',
u'JAS',
u'1PE',
u'2PE',
u'1JN',
u'2JN',
u'3JN',
u'JUD',
u'REV' ]

bookNames = ['Genesis',
            'Exodus',
            'Leviticus',
            'Numbers',
            'Deuteronomy',
            'Joshua',
            'Judges',
            'Ruth',
            '1 Samuel',
            '2 Samuel',
            '1 Kings',
            '2 Kings',
            '1 Chronicles',
            '2 Chronicles',
            'Ezra',
            'Nehemiah',
            'Esther',
            'Job',
            'Psalms',
            'Proverbs',
            'Ecclesiastes',
            'Song of Solomon',
            'Isaiah',
            'Jeremiah',
            'Lamentations',
            'Ezekiel',
            'Daniel',
            'Hosea',
            'Joel',
            'Amos',
            'Obadiah',
            'Jonah',
            'Micah',
            'Nahum',
            'Habakkuk',
            'Zephaniah',
            'Haggai',
            'Zechariah',
            'Malachi',
            'Matthew',
            'Mark',
            'Luke',
            'John',
            'Acts',
            'Romans',
            '1 Corinthians',
            '2 Corinthians',
            'Galatians',
            'Ephesians',
            'Philippians',
            'Colossians',
            '1 Thessalonians',
            '2 Thessalonians',
            '1 Timothy',
            '2 Timothy',
            'Titus',
            'Philemon',
            'Hebrews',
            'James',
            '1 Peter',
            '2 Peter',
            '1 John',
            '2 John',
            '3 John',
            'Jude',
            'Revelation']

books = bookNames 

def bookKeyForIdValue(id):
    e = id.find(' ')
    i = id if e == -1 else id[:e]
    return bookKeys[i] 

def bookID(usfm):
    s = usfm.find(u'\id ') + 4
    e = usfm.find(u' ', s)
    e2 = usfm.find(u'\n', s)
    e = e if e < e2 else e2
    return usfm[s:e].strip()
    
def bookName(usfm):
    id = bookID(usfm)
    index = silNames.index(id)
    return bookNames[index]

    
def loadBooks(path):
    books = {}
    dirList=os.listdir(path)
    for fname in dirList:
      if fname[-5:] == '.usfm':
          f = open(path + '/' + fname)
          usfm = f.read().decode('utf-8-sig')
          books[bookID(usfm)] = usfm
          f.close()
    return books


